apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: raveelkashif1.azurecr.io/book
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://raveelkashif_sit722_7_2p_user:trCgEFFTBDpcqghOWKT9u6nckb8NvBjH@dpg-crhv795umphs73ca6h2g-a.oregon-postgres.render.com/raveelkashif_sit722_7_2p"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: raveelkashif1.azurecr.io/inventory
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://raveelkashif_sit722_7_2p_user:trCgEFFTBDpcqghOWKT9u6nckb8NvBjH@dpg-crhv795umphs73ca6h2g-a.oregon-postgres.render.com/raveelkashif_sit722_7_2p"
        

---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
  - name: book-catalog
    protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
  - name: inventory-management
    protocol: TCP
    port: 8001
    targetPort: 8001
